### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by TomasVotruba** [mnapoli/fluent-symfony#23]
#Hi @mnapoli, 

just wanted to say great job! I didn't find any post about this on your blog, so I write here. This is not an issue at all :D 

**I love the PHP 7 version, used Symfony 3.2 versions, the README and the feature itself!**

Thank you for creating this I would say "exemplary" package.

**Comment by mnapoli** [comment]
Hi, thanks for the kind words :) I also forward that message to @rejinka and @pitchart who have been working on this project as well, we'll see where it goes (and maybe at some point it might make sense to move it into its own organisation but let's wait and see [if some people actually start to use it](https://packagist.org/packages/mnapoli/fluent-symfony/stats))

I'll be closing since it's not an issue ;)
